
export interface Integration {
  id: string;
  name: string;
  description: string;
  category: 'browser' | 'public_api';
  contextPrompt: string;
}

export const BROWSER_APIS: Integration[] = [
  { id: 'geo', name: 'Geolocation API', description: 'Access user location (lat/long).', category: 'browser', contextPrompt: 'Use navigator.geolocation to get current position.' },
  { id: 'cam', name: 'Camera / MediaStream', description: 'Access camera and microphone.', category: 'browser', contextPrompt: 'Use navigator.mediaDevices.getUserMedia for camera/audio.' },
  { id: 'speech_rec', name: 'Speech Recognition', description: 'Convert voice to text.', category: 'browser', contextPrompt: 'Use window.SpeechRecognition or webkitSpeechRecognition.' },
  { id: 'speech_syn', name: 'Speech Synthesis', description: 'Text-to-speech engine.', category: 'browser', contextPrompt: 'Use window.speechSynthesis for TTS.' },
  { id: 'share', name: 'Web Share API', description: 'Native sharing dialog.', category: 'browser', contextPrompt: 'Use navigator.share() to open native share sheet.' },
  { id: 'vibrate', name: 'Vibration API', description: 'Haptic feedback.', category: 'browser', contextPrompt: 'Use navigator.vibrate() for haptics.' },
  { id: 'battery', name: 'Battery Status API', description: 'Check battery level.', category: 'browser', contextPrompt: 'Use navigator.getBattery().' },
  { id: 'online', name: 'Network Status', description: 'Check if user is online/offline.', category: 'browser', contextPrompt: 'Listen to window "online" and "offline" events.' },
  { id: 'storage', name: 'Local Storage', description: 'Persist data on device.', category: 'browser', contextPrompt: 'Use localStorage for data persistence.' },
  { id: 'indexeddb', name: 'IndexedDB', description: 'Large-scale local database.', category: 'browser', contextPrompt: 'Use IndexedDB for complex local data storage.' },
  { id: 'notif', name: 'Notifications API', description: 'System push notifications.', category: 'browser', contextPrompt: 'Request Notification.requestPermission() and create new Notification().' },
  { id: 'clipboard', name: 'Clipboard API', description: 'Copy/Paste functionality.', category: 'browser', contextPrompt: 'Use navigator.clipboard.writeText() and readText().' },
  { id: 'pip', name: 'Picture-in-Picture', description: 'Floating video player.', category: 'browser', contextPrompt: 'Use videoElement.requestPictureInPicture().' },
  { id: 'fullscreen', name: 'Fullscreen API', description: 'Full screen mode.', category: 'browser', contextPrompt: 'Use element.requestFullscreen().' },
  { id: 'orientation', name: 'Device Orientation', description: 'Gyroscope/Rotation data.', category: 'browser', contextPrompt: 'Listen for "deviceorientation" events.' },
  { id: 'motion', name: 'Device Motion', description: 'Accelerometer data.', category: 'browser', contextPrompt: 'Listen for "devicemotion" events.' },
  { id: 'bluetooth', name: 'Web Bluetooth', description: 'Connect to BLE devices.', category: 'browser', contextPrompt: 'Use navigator.bluetooth.requestDevice().' },
  { id: 'usb', name: 'Web USB', description: 'Connect to USB devices.', category: 'browser', contextPrompt: 'Use navigator.usb.requestDevice().' },
  { id: 'gamepad', name: 'Gamepad API', description: 'Controller input support.', category: 'browser', contextPrompt: 'Use navigator.getGamepads().' },
  { id: 'midi', name: 'Web MIDI', description: 'Musical Instrument Digital Interface.', category: 'browser', contextPrompt: 'Use navigator.requestMIDIAccess().' },
  { id: 'audio', name: 'Web Audio API', description: 'Complex audio synthesis/processing.', category: 'browser', contextPrompt: 'Use new AudioContext() for sound generation.' },
  { id: 'canvas', name: 'Canvas API', description: '2D Graphics drawing.', category: 'browser', contextPrompt: 'Use canvas.getContext("2d").' },
  { id: 'intersection', name: 'Intersection Observer', description: 'Detect when element is visible.', category: 'browser', contextPrompt: 'Use new IntersectionObserver().' },
  { id: 'resize', name: 'Resize Observer', description: 'Detect element size changes.', category: 'browser', contextPrompt: 'Use new ResizeObserver().' },
  { id: 'mutation', name: 'Mutation Observer', description: 'Detect DOM changes.', category: 'browser', contextPrompt: 'Use new MutationObserver().' },
  { id: 'broadcast', name: 'Broadcast Channel', description: 'Cross-tab communication.', category: 'browser', contextPrompt: 'Use new BroadcastChannel().' },
  { id: 'worker', name: 'Web Workers', description: 'Background threads.', category: 'browser', contextPrompt: 'Use new Worker().' },
  { id: 'socket', name: 'WebSockets', description: 'Real-time bidirectional comms.', category: 'browser', contextPrompt: 'Use new WebSocket().' },
  { id: 'crypto', name: 'Web Crypto API', description: 'Cryptographic functions.', category: 'browser', contextPrompt: 'Use crypto.subtle for encryption/hashing.' },
  { id: 'payment', name: 'Payment Request API', description: 'Native payment UI.', category: 'browser', contextPrompt: 'Use new PaymentRequest().' }
];

export const PUBLIC_APIS: Integration[] = [
  { id: 'meal', name: 'TheMealDB', description: 'Recipes and meals.', category: 'public_api', contextPrompt: 'Use https://www.themealdb.com/api/json/v1/1/ for recipes.' },
  { id: 'cocktail', name: 'TheCocktailDB', description: 'Drink recipes.', category: 'public_api', contextPrompt: 'Use https://www.thecocktaildb.com/api/json/v1/1/ for drinks.' },
  { id: 'poke', name: 'PokeAPI', description: 'Pokemon data.', category: 'public_api', contextPrompt: 'Use https://pokeapi.co/api/v2/ for Pokemon data.' },
  { id: 'restcountries', name: 'REST Countries', description: 'Country information.', category: 'public_api', contextPrompt: 'Use https://restcountries.com/v3.1/all for country data.' },
  { id: 'openlibrary', name: 'Open Library', description: 'Books and covers.', category: 'public_api', contextPrompt: 'Use https://openlibrary.org/dev/docs/api/search for books.' },
  { id: 'randomuser', name: 'Random User', description: 'Mock user data.', category: 'public_api', contextPrompt: 'Use https://randomuser.me/api/ for mock profiles.' },
  { id: 'dadjoke', name: 'Dad Jokes', description: 'Random dad jokes.', category: 'public_api', contextPrompt: 'Headers: {Accept: application/json}, URL: https://icanhazdadjoke.com/' },
  { id: 'numbers', name: 'Numbers API', description: 'Facts about numbers.', category: 'public_api', contextPrompt: 'Use http://numbersapi.com/ for number facts.' },
  { id: 'nasa', name: 'NASA APOD', description: 'Astronomy Picture of the Day.', category: 'public_api', contextPrompt: 'Use https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY' },
  { id: 'picsum', name: 'Lorem Picsum', description: 'Random placeholder images.', category: 'public_api', contextPrompt: 'Use https://picsum.photos/v2/list for images.' },
  { id: 'dog', name: 'Dog API', description: 'Random dog images.', category: 'public_api', contextPrompt: 'Use https://dog.ceo/api/breeds/image/random' },
  { id: 'cat', name: 'Cat Facts', description: 'Facts about cats.', category: 'public_api', contextPrompt: 'Use https://catfact.ninja/fact' },
  { id: 'bored', name: 'Bored API', description: 'Activity suggestions.', category: 'public_api', contextPrompt: 'Use https://www.boredapi.com/api/activity' },
  { id: 'agify', name: 'Agify.io', description: 'Predict age from name.', category: 'public_api', contextPrompt: 'Use https://api.agify.io?name=...' },
  { id: 'genderize', name: 'Genderize.io', description: 'Predict gender from name.', category: 'public_api', contextPrompt: 'Use https://api.genderize.io?name=...' },
  { id: 'nationalize', name: 'Nationalize.io', description: 'Predict nationality.', category: 'public_api', contextPrompt: 'Use https://api.nationalize.io?name=...' },
  { id: 'ipify', name: 'IPify', description: 'Get public IP.', category: 'public_api', contextPrompt: 'Use https://api.ipify.org?format=json' },
  { id: 'coindesk', name: 'CoinDesk', description: 'Bitcoin price index.', category: 'public_api', contextPrompt: 'Use https://api.coindesk.com/v1/bpi/currentprice.json' },
  { id: 'universities', name: 'Universities', description: 'List of universities.', category: 'public_api', contextPrompt: 'Use http://universities.hipolabs.com/search?country=...' },
  { id: 'zip', name: 'Zippopotam', description: 'Zip code info.', category: 'public_api', contextPrompt: 'Use http://api.zippopotam.us/us/90210' },
  { id: 'frankfurter', name: 'Frankfurter', description: 'Currency exchange rates.', category: 'public_api', contextPrompt: 'Use https://api.frankfurter.app/latest' },
  { id: 'lyrics', name: 'Lyrics.ovh', description: 'Song lyrics.', category: 'public_api', contextPrompt: 'Use https://api.lyrics.ovh/v1/artist/title' },
  { id: 'tvmaze', name: 'TV Maze', description: 'TV Show info.', category: 'public_api', contextPrompt: 'Use https://api.tvmaze.com/search/shows?q=...' },
  { id: 'openbrewery', name: 'Open Brewery', description: 'Breweries list.', category: 'public_api', contextPrompt: 'Use https://api.openbrewerydb.org/breweries' },
  { id: 'advice', name: 'Advice Slip', description: 'Random advice.', category: 'public_api', contextPrompt: 'Use https://api.adviceslip.com/advice' },
  { id: 'funtrans', name: 'Fun Translations', description: 'Yoda/Pirate speak.', category: 'public_api', contextPrompt: 'Use https://api.funtranslations.com/translate/...' },
  { id: 'marvel', name: 'Marvel (Public Key)', description: 'Comic data.', category: 'public_api', contextPrompt: 'Requires generating hash. Prefer simpler APIs unless requested.' },
  { id: 'rickmorty', name: 'Rick and Morty', description: 'Character data.', category: 'public_api', contextPrompt: 'Use https://rickandmortyapi.com/api/character' },
  { id: 'dict', name: 'Dictionary API', description: 'Word definitions.', category: 'public_api', contextPrompt: 'Use https://api.dictionaryapi.dev/api/v2/entries/en/hello' },
  { id: 'quotes', name: 'Quotable', description: 'Famous quotes.', category: 'public_api', contextPrompt: 'Use https://api.quotable.io/random' },
  { id: 'makeup', name: 'Makeup API', description: 'Cosmetic products.', category: 'public_api', contextPrompt: 'Use http://makeup-api.herokuapp.com/api/v1/products.json' },
  { id: 'f1', name: 'Ergast F1', description: 'Formula 1 data.', category: 'public_api', contextPrompt: 'Use http://ergast.com/api/f1/current.json' },
  { id: 'coincap', name: 'CoinCap', description: 'Crypto market data.', category: 'public_api', contextPrompt: 'Use https://api.coincap.io/v2/assets' },
  { id: '7timer', name: '7Timer', description: 'Weather forecast.', category: 'public_api', contextPrompt: 'Use http://www.7timer.info/bin/api.pl' },
  { id: 'art', name: 'Art Institute Chicago', description: 'Artworks.', category: 'public_api', contextPrompt: 'Use https://api.artic.edu/api/v1/artworks' },
  { id: 'jikan', name: 'Jikan (MAL)', description: 'Anime/Manga info.', category: 'public_api', contextPrompt: 'Use https://api.jikan.moe/v4/anime' },
  { id: 'gutendex', name: 'Gutendex', description: 'Project Gutenberg books.', category: 'public_api', contextPrompt: 'Use https://gutendex.com/books' },
  { id: 'deck', name: 'Deck of Cards', description: 'Card game logic.', category: 'public_api', contextPrompt: 'Use https://deckofcardsapi.com/api/deck/new/shuffle/' },
  { id: 'xkcd', name: 'XKCD', description: 'Comics.', category: 'public_api', contextPrompt: 'Use https://xkcd.com/info.0.json' },
  { id: 'trefle', name: 'Trefle', description: 'Plants (Check key).', category: 'public_api', contextPrompt: 'Skip if key needed.' },
  { id: 'punk', name: 'Punk API', description: 'Beer recipes.', category: 'public_api', contextPrompt: 'Use https://api.punkapi.com/v2/beers' },
  { id: 'opendota', name: 'OpenDota', description: 'Dota 2 stats.', category: 'public_api', contextPrompt: 'Use https://api.opendota.com/api/matches/...' },
  { id: 'studio', name: 'Studio Ghibli', description: 'Ghibli films.', category: 'public_api', contextPrompt: 'Use https://ghibliapi.vercel.app/films' },
  { id: 'hp', name: 'Harry Potter', description: 'HP spells/characters.', category: 'public_api', contextPrompt: 'Use https://hp-api.onrender.com/api/characters' },
  { id: 'got', name: 'Game of Thrones', description: 'GoT characters.', category: 'public_api', contextPrompt: 'Use https://thronesapi.com/api/v2/Characters' },
  { id: 'amiibo', name: 'AmiiboAPI', description: 'Nintendo Amiibos.', category: 'public_api', contextPrompt: 'Use https://www.amiiboapi.com/api/amiibo/' },
  { id: 'sun', name: 'Sunrise/Sunset', description: 'Solar times.', category: 'public_api', contextPrompt: 'Use https://api.sunrise-sunset.org/json?lat=...&lng=...' },
  { id: 'wger', name: 'Wger Workout', description: 'Exercises.', category: 'public_api', contextPrompt: 'Use https://wger.de/api/v2/exercise/' },
  { id: 'animechan', name: 'AnimeChan', description: 'Anime quotes.', category: 'public_api', contextPrompt: 'Use https://animechan.xyz/api/random' },
  { id: 'met', name: 'Met Museum', description: 'Museum objects.', category: 'public_api', contextPrompt: 'Use https://collectionapi.metmuseum.org/public/collection/v1/objects' }
];
